# Generated by Django 4.1.5 on 2023-02-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpreferences_session_alter_userpreferences_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='timezone',
        ),
    ]
