# Generated by Django 4.1.5 on 2023-01-31 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=60)),
                ('datetime', models.TimeField()),
                ('datetimeEpoch', models.IntegerField()),
                ('temp', models.FloatField()),
                ('feelslike', models.FloatField()),
                ('humidity', models.FloatField()),
                ('precip', models.FloatField()),
                ('snow', models.FloatField()),
                ('preciptype', models.CharField(blank=True, max_length=50, null=True)),
                ('pressure', models.FloatField()),
                ('cloudcover', models.FloatField()),
                ('uvindex', models.FloatField()),
                ('conditions', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=30)),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('moonphase', models.FloatField()),
                ('daily_description', models.CharField(max_length=150)),
                ('last_modified', models.TimeField(auto_now=True)),
                ('order', models.SmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('loc', 'author')},
            },
        ),
    ]
