# Generated by Django 4.1.5 on 2023-01-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='units',
            field=models.CharField(choices=[('Celsius', 'Celsius'), ('Fahrenheit', 'Fahrenheit')], default='Celsius', max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='locs',
            field=models.TextField(max_length=500),
        ),
    ]
