# Generated by Django 4.1.5 on 2023-02-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_weather', '0003_alter_location_datetimeepoch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='datetime',
        ),
    ]
