# Generated by Django 4.1.5 on 2023-02-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_weather', '0005_rename_datetimeepoch_location_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='datetime',
            new_name='datetimeEpoch',
        ),
    ]
