# Generated by Django 4.1.5 on 2023-02-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_weather', '0007_location_session_alter_location_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
    ]
