# Generated by Django 4.1.5 on 2023-02-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_weather', '0010_location_tz_display_dt_location_tz_display_lm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='sunrise',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='sunset',
            field=models.DateTimeField(),
        ),
    ]
