# Generated by Django 4.1.5 on 2023-02-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_weather', '0012_alter_location_sunrise_alter_location_sunset'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='pretty_loc',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='daily_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc',
            field=models.CharField(max_length=100),
        ),
    ]
